---
title: "Hex sticker for {brms.mmrm}"
rmarkdown::html_document:
  theme: "default"
  highlight: "default"
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  prompt = TRUE,
  comment = "#",
  out.width = "100%",
  fig.path = "figures/"
)
```

## Prerequisites

Load packages:
```{r packages, eval=TRUE, echo=TRUE}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggdist)
  library(hexSticker)
  library(sysfonts)
})
```

Define colors:
```{r colors, eval=TRUE, echo=TRUE}
hex_cols <- c("#2b2f44", "#edf7f8", "#1d6fa7", "#f3594d", "#632f56", "#b44b33")
```

(See: https://huemint.com/illustration-1/#palette=2b2f44-edf7f8-1d6fa7-f3594d-632f56-b44b33)

## Data

```{r data1, eval=TRUE, echo=TRUE}
set.seed(42)
n <- 10^4
dat <- expand.grid(
  subject = paste0("pat_", sprintf("%04d", 1:n)) |> factor(),
  visit = c(1, 2, 3, 4) |> factor()
  ) |>
  mutate(baseline = rnorm(n = n(), mean = 90, sd = 20)) |>
  group_by(subject) |>
  mutate(trt = sample(x = c(0, 1), size = 1)) |>
  ungroup() |>
  mutate(trt =factor(trt)) |>
  arrange(subject, visit)
f <- as.formula( ~ -1 + trt : visit)
X <-  model.matrix(object = f, data = data.frame(dat))
betas <- numeric(length = dim(X)[2])
names(betas) <- colnames(X)
betas[1] <- 50
betas[2] <- 50 + 12
betas[3] <- 20
betas[4] <- 20 + 18
betas[5] <- -5
betas[6] <- -5 + 32
betas[7] <- -30
betas[8] <- -30 + 35
err <- rnorm(n = n*4, mean = 0, sd = 5)
y <-  c(X %*% betas + err)
dat <- bind_cols(dat, "y" = y) |>
  mutate(visit_num = as.numeric(visit),
         chg = y - baseline)
dat
```

## Plots

### Plot 1

```{r plot1, eval=TRUE, echo=TRUE, fig.width=8, fig.height=6, dev=c('png', 'pdf'), out.width="100%", fig.cap='MMRM plot 1.'}
p1 <- ggplot(
  data = dat,
  mapping = aes(
    x = visit,
    y = chg,
    fill = trt)
  ) +
  scale_fill_manual(values = alpha(c("0" = hex_cols[3], "1" = hex_cols[4]), 0.45)) +
  scale_color_manual(values = c("0" = hex_cols[3], "1" = hex_cols[4])) +  
  stat_halfeye(mapping = aes(color = trt),
    position = position_dodgejust(width = 0.95)
    ) +
 theme_void() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "none",
    plot.margin = margin(t = 5, r = 5, b = 5, l = 5, unit = "mm"),
    plot.background = element_rect(fill = hex_cols[1], color = NA)
  )
p1
```


### Plot 2

The distance between the categories on the x-axis is now determined by the 
numeric values of the `visit_num` variable, and can be adjusted using this 
variable to increase or decrease the distance as per your preference.


```{r data_plot2, eval=TRUE, echo=TRUE}
vec <- unique(dat$visit_num)
scaling_factor <- 1.35
diffs <- diff(vec)
scaled_diffs <- diffs * scaling_factor
transformed_vec <- c(vec[1], vec[1] + cumsum(scaled_diffs))
unique_visit_num <- sort(unique(dat$visit_num))
replacement <- setNames(object = transformed_vec, nm = unique_visit_num)
replacement 
```

```{r plot2, eval=TRUE, echo=TRUE, fig.width=8, fig.height=6, dev=c('png', 'pdf'), out.width="100%", fig.cap='MMRM plot 2.'}
p2 <- dat |>
  mutate(
    visit_num = replacement[as.character(visit_num)]
  ) |>
ggplot(
  mapping = aes(
    x = visit_num,
    y = chg,
    fill = trt)
  ) +
  scale_fill_manual(values = alpha(c("0" = hex_cols[3], "1" = hex_cols[4]), 0.6)) +
  scale_color_manual(values = c("0" = hex_cols[3], "1" = hex_cols[4])) +  
  stat_halfeye(mapping = aes(color = trt),
               width = 0.95,
    position = position_dodgejust(width = 1)
    ) +
 theme_void() +
 theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "none",
    plot.margin = margin(t = 3, r = 3, b = 3, l = 3, unit = "mm"),
    plot.background = element_rect(fill = hex_cols[1], color = NA)
  ) +
  scale_x_continuous(breaks = unique(dat$visit_num),
                     labels = unique(dat$visit))
p2
```

### Plot 3
```{r data_plot3, eval=TRUE, echo=TRUE}
vec <- unique(dat$visit_num)
scaling_factor <- 5
diffs <- diff(vec)
scaled_diffs <- diffs * scaling_factor
transformed_vec <- c(vec[1], vec[1] + cumsum(scaled_diffs))
unique_visit_num <- sort(unique(dat$visit_num))
replacement <- setNames(object = transformed_vec, nm = unique_visit_num)
replacement 
```

```{r plot3, eval=TRUE, echo=TRUE, fig.width=9, fig.height=6, dev=c('png', 'pdf'), out.width="100%", fig.cap='MMRM plot 3.'}
p3 <- dat |> 
  ggplot(
    mapping = aes(
      x = visit,
      y = chg,
      fill = trt)
    ) +
  scale_fill_manual(values = alpha(c("0" = hex_cols[4], "1" = hex_cols[3]), 0.6)) +
  scale_color_manual(values = c("0" = hex_cols[4], "1" = hex_cols[3])) +    
  geom_violin(mapping = aes(color = trt), position = position_dodge(width = 0.4)) +
  geom_boxplot(mapping = aes(color = trt), width = 0.3, position = position_dodge(width = 0.4)) +
 theme_void() +
 theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "none",
    plot.margin = margin(t = 3, r = 3, b = 10, l = 3, unit = "mm")
  )
p3
```

## Hex sticker

```{r hex_sticker, eval=TRUE, echo=TRUE, fig.width=3, fig.height=3.47155255544841, dev=c('pdf','png'), out.width="100%", fig.cap='Hex sticker.'}
font_add_google(name = "Inter", family = "Economica")
s <- sticker(
  p2,
  package = "brms.mmrm",
  p_size = 8,
  s_x = 1,
  s_y = 0.8,
  s_width = 8/4.5,
  s_height = 6/4.5,
  filename = "hex_sticker.svg",
  p_fontface = "bold",
  p_fontfamily = "Economica",
  h_fill = hex_cols[1],
  h_color = hex_cols[6],
  p_color = hex_cols[2],
  dpi = 1200
)
s
```











