---
title: "Usage"
output:
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{Usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



A mixed model of repeated measures (MMRM) analyzes longitudinal clinical trial data. In a longitudinal dataset, there are multiple patients, and each patient has multiple observations at a common set of discrete points in time.

# Data

To use the `brms.mmrm` package, begin with a longitudinal dataset with one row per patient observation and columns for the response variable, treatment group indicator, discrete time point indicator, patient ID variable, and optional baseline covariates such as age and region. If you do not have a real dataset of your own, you can simulate one from the package. The following dataset has the raw response variable, the  essential factor variables, and continuous baseline covariates.^[Covariates can be categorical too.] In general, the outcome variable can either be the raw response or change from baseline.


```r
library(brms.mmrm)
library(dplyr)
library(magrittr)
set.seed(0L)
raw_data <- brm_simulate_simple(
  n_group = 3,
  n_patient = 100,
  n_time = 4
) %>%
  extract2("data") %>%
  brm_simulate_continuous(c("biomarker1", "biomarker2", "biomarker3"))

raw_data
#> # A tibble: 1,200 × 7
#>    response group   time   patient     biomarker1 biomarker2 biomarker3
#>       <dbl> <chr>   <chr>  <chr>            <dbl>      <dbl>      <dbl>
#>  1    1.11  group_1 time_1 patient_001      1.31      -0.361      1.52 
#>  2    2.15  group_1 time_2 patient_001      1.31      -0.361      1.52 
#>  3    2.54  group_1 time_3 patient_001      1.31      -0.361      1.52 
#>  4   -1.73  group_1 time_4 patient_001      1.31      -0.361      1.52 
#>  5    1.11  group_1 time_1 patient_002      0.107     -2.44      -0.139
#>  6    2.64  group_1 time_2 patient_002      0.107     -2.44      -0.139
#>  7    1.69  group_1 time_3 patient_002      0.107     -2.44      -0.139
#>  8    0.783 group_1 time_4 patient_002      0.107     -2.44      -0.139
#>  9    0.118 group_1 time_1 patient_003      1.44      -0.419     -1.54 
#> 10    2.48  group_1 time_2 patient_003      1.44      -0.419     -1.54 
#> # ℹ 1,190 more rows
```

Next, create a special classed dataset that the package will recognize. The classed data object contains a pre-processed version of the data, along with attributes to declare the outcome variable, whether the outcome is response or change from baseline, the treatment group variable, the discrete time point variable, control group, baseline time point, and the covariates selected for analysis.


```r
data <- brm_data(
  data = raw_data,
  outcome = "response",
  role = "response",
  group = "group",
  patient = "patient",
  time = "time",
  covariates = c("biomarker1", "biomarker2"),
  reference_group = "group_1",
  reference_time = "time_1"
)

data
#> # A tibble: 1,200 × 6
#>    response group   time   patient     biomarker1 biomarker2
#>       <dbl> <chr>   <chr>  <chr>            <dbl>      <dbl>
#>  1    1.11  group_1 time_1 patient_001      1.31      -0.361
#>  2    2.15  group_1 time_2 patient_001      1.31      -0.361
#>  3    2.54  group_1 time_3 patient_001      1.31      -0.361
#>  4   -1.73  group_1 time_4 patient_001      1.31      -0.361
#>  5    1.11  group_1 time_1 patient_002      0.107     -2.44 
#>  6    2.64  group_1 time_2 patient_002      0.107     -2.44 
#>  7    1.69  group_1 time_3 patient_002      0.107     -2.44 
#>  8    0.783 group_1 time_4 patient_002      0.107     -2.44 
#>  9    0.118 group_1 time_1 patient_003      1.44      -0.419
#> 10    2.48  group_1 time_2 patient_003      1.44      -0.419
#> # ℹ 1,190 more rows

class(data)
#> [1] "brms_mmrm_data" "tbl_df"         "tbl"            "data.frame"

roles <- attributes(data)
roles$row.names <- NULL
str(roles)
#> List of 14
#>  $ names              : chr [1:6] "response" "group" "time" "patient" ...
#>  $ class              : chr [1:4] "brms_mmrm_data" "tbl_df" "tbl" "data.frame"
#>  $ brm_outcome        : chr "response"
#>  $ brm_role           : chr "response"
#>  $ brm_group          : chr "group"
#>  $ brm_time           : chr "time"
#>  $ brm_patient        : chr "patient"
#>  $ brm_covariates     : chr [1:2] "biomarker1" "biomarker2"
#>  $ brm_reference_group: chr "group_1"
#>  $ brm_reference_time : chr "time_1"
#>  $ brm_levels_group   : chr [1:3] "group_1" "group_2" "group_3"
#>  $ brm_levels_time    : chr [1:4] "time_1" "time_2" "time_3" "time_4"
#>  $ brm_labels_group   : chr [1:3] "group_1" "group_2" "group_3"
#>  $ brm_labels_time    : chr [1:4] "time_1" "time_2" "time_3" "time_4"
```

# Formula

Next, choose a `brms` model formula for the fixed effect and variance parameters. The `brm_formula()` function from `brms.mmrm` makes this process easier. A cell means parameterization for this particular model can be expressed as follows. It specifies one fixed effect parameter for each combination of treatment group and time point, and it makes the specification of informative priors straightforward through the `prior` argument of `brm_model()`.


```r
brm_formula(
  data = data,
  intercept = FALSE,
  baseline = FALSE,
  group = FALSE,
  time = FALSE,
  baseline_time = FALSE,
  group_time = TRUE
)
#> response ~ 0 + group:time + biomarker1 + biomarker2 + unstr(time = time, gr = patient) 
#> sigma ~ 0 + time
```

For the purposes of our example, we choose a fully parameterized analysis of the raw response.


```r
formula <- brm_formula(
  data = data,
  intercept = TRUE,
  baseline = FALSE,
  group = TRUE,
  time = TRUE,
  baseline_time = FALSE,
  group_time = TRUE
)

formula
#> response ~ group + group:time + time + biomarker1 + biomarker2 + unstr(time = time, gr = patient) 
#> sigma ~ 0 + time
```

# Parameterization

The formula is not the only factor
that ultimately determines the fixed effect parameterization.
The ordering of the categorical variables in the data,
as well as the `contrast` option in R, affect the
construction of the model matrix. To see the model
matrix that will ultimately be used in `brm_model()`,
run `brms::make_standata()` and examine the `X` element
of the returned list.

The `contrast` option accepts a named vector of two character vectors which govern `model.matrix()` contrasts for unordered and ordered variables, respectively.


```r
options(contrasts = c(unordered = "contr.SAS", ordered = "contr.poly"))
```

The `make_standata()` function lets you see the data that `brms` will generate for Stan. This includes the fixed effects model matrix `X`. Note the differences in the `groupgroup_*` additive terms between the matrix below and the one above.


```r
head(brms::make_standata(formula = formula, data = data)$X)
#>   Intercept groupgroup_1 groupgroup_2 timetime_1 timetime_2 timetime_3
#> 1         1            1            0          1          0          0
#> 2         1            1            0          0          1          0
#> 3         1            1            0          0          0          1
#> 4         1            1            0          0          0          0
#> 5         1            1            0          1          0          0
#> 6         1            1            0          0          1          0
#>   biomarker1 biomarker2 groupgroup_1:timetime_1 groupgroup_2:timetime_1
#> 1  1.3126508 -0.3608809                       1                       0
#> 2  1.3126508 -0.3608809                       0                       0
#> 3  1.3126508 -0.3608809                       0                       0
#> 4  1.3126508 -0.3608809                       0                       0
#> 5  0.1068624 -2.4441488                       1                       0
#> 6  0.1068624 -2.4441488                       0                       0
#>   groupgroup_1:timetime_2 groupgroup_2:timetime_2 groupgroup_1:timetime_3
#> 1                       0                       0                       0
#> 2                       1                       0                       0
#> 3                       0                       0                       1
#> 4                       0                       0                       0
#> 5                       0                       0                       0
#> 6                       1                       0                       0
#>   groupgroup_2:timetime_3
#> 1                       0
#> 2                       0
#> 3                       0
#> 4                       0
#> 5                       0
#> 6                       0
```

If you choose a different contrast method, a different model matrix may result.


```r
options(
  contrasts = c(unordered = "contr.treatment", ordered = "contr.poly")
)
# different model matrix than before:
head(brms::make_standata(formula = formula, data = data)$X)
#>   Intercept groupgroup_2 groupgroup_3 timetime_2 timetime_3 timetime_4
#> 1         1            0            0          0          0          0
#> 2         1            0            0          1          0          0
#> 3         1            0            0          0          1          0
#> 4         1            0            0          0          0          1
#> 5         1            0            0          0          0          0
#> 6         1            0            0          1          0          0
#>   biomarker1 biomarker2 groupgroup_2:timetime_2 groupgroup_3:timetime_2
#> 1  1.3126508 -0.3608809                       0                       0
#> 2  1.3126508 -0.3608809                       0                       0
#> 3  1.3126508 -0.3608809                       0                       0
#> 4  1.3126508 -0.3608809                       0                       0
#> 5  0.1068624 -2.4441488                       0                       0
#> 6  0.1068624 -2.4441488                       0                       0
#>   groupgroup_2:timetime_3 groupgroup_3:timetime_3 groupgroup_2:timetime_4
#> 1                       0                       0                       0
#> 2                       0                       0                       0
#> 3                       0                       0                       0
#> 4                       0                       0                       0
#> 5                       0                       0                       0
#> 6                       0                       0                       0
#>   groupgroup_3:timetime_4
#> 1                       0
#> 2                       0
#> 3                       0
#> 4                       0
#> 5                       0
#> 6                       0
```

# Priors

Some analyses require informative priors, others require non-informative ones. Please use [`brms`](https://paul-buerkner.github.io/brms/) to construct a prior suitable for your analysis. The [`brms`](https://paul-buerkner.github.io/brms/) package has documentation on how its default priors are constructed and how to set your own priors. Once you have an R object that represents the joint prior distribution of your model, you can pass it to the `brm_model()` function described below. The `get_prior()` function shows the default priors for a given dataset and model formula.


```r
brms::get_prior(data = data, formula = formula)
#>                   prior     class                    coef group resp  dpar
#>                  (flat)         b                                         
#>                  (flat)         b              biomarker1                 
#>                  (flat)         b              biomarker2                 
#>                  (flat)         b            groupgroup_2                 
#>                  (flat)         b groupgroup_2:timetime_2                 
#>                  (flat)         b groupgroup_2:timetime_3                 
#>                  (flat)         b groupgroup_2:timetime_4                 
#>                  (flat)         b            groupgroup_3                 
#>                  (flat)         b groupgroup_3:timetime_2                 
#>                  (flat)         b groupgroup_3:timetime_3                 
#>                  (flat)         b groupgroup_3:timetime_4                 
#>                  (flat)         b              timetime_2                 
#>                  (flat)         b              timetime_3                 
#>                  (flat)         b              timetime_4                 
#>                  lkj(1)   cortime                                         
#>  student_t(3, 0.9, 2.5) Intercept                                         
#>                  (flat)         b                                    sigma
#>                  (flat)         b              timetime_1            sigma
#>                  (flat)         b              timetime_2            sigma
#>                  (flat)         b              timetime_3            sigma
#>                  (flat)         b              timetime_4            sigma
#>  nlpar lb ub       source
#>                   default
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>                   default
#>                   default
#>                   default
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
#>              (vectorized)
```

# Model

To run an MMRM, use the `brm_model()` function. This function calls `brms::brm()` behind the scenes, using the formula and prior you set in the `formula` and `prior` arguments.


```r
model <- brm_model(data = data, formula = formula, refresh = 0)
```



The result is a `brms` model object.


```r
model
#>  Family: gaussian 
#>   Links: mu = identity; sigma = log 
#> Formula: response ~ group + group:time + time + biomarker1 + biomarker2 + unstr(time = time, gr = patient) 
#>          sigma ~ 0 + time
#>    Data: data[!is.na(data[[attr(data, "brm_outcome")]]), ] (Number of observations: 1200) 
#>   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
#>          total post-warmup draws = 4000
#> 
#> Correlation Structures:
#>                        Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS
#> cortime(time_1,time_2)     0.42      0.05     0.33     0.51 1.00     3516
#> cortime(time_1,time_3)    -0.80      0.02    -0.84    -0.76 1.00     2361
#> cortime(time_2,time_3)    -0.54      0.04    -0.62    -0.46 1.00     3653
#> cortime(time_1,time_4)    -0.29      0.05    -0.39    -0.18 1.00     3964
#> cortime(time_2,time_4)     0.03      0.06    -0.09     0.14 1.00     3444
#> cortime(time_3,time_4)    -0.10      0.06    -0.21     0.01 1.00     3847
#>                        Tail_ESS
#> cortime(time_1,time_2)     3008
#> cortime(time_1,time_3)     2594
#> cortime(time_2,time_3)     3411
#> cortime(time_1,time_4)     3061
#> cortime(time_2,time_4)     3347
#> cortime(time_3,time_4)     3221
#> 
#> Population-Level Effects: 
#>                         Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS
#> Intercept                   1.22      0.09     1.05     1.39 1.01     1290
#> groupgroup_2               -1.54      0.12    -1.77    -1.30 1.01     1524
#> groupgroup_3                0.18      0.13    -0.07     0.43 1.01     1248
#> timetime_2                  1.31      0.10     1.12     1.51 1.00     1897
#> timetime_3                  0.51      0.17     0.17     0.85 1.01     1597
#> timetime_4                 -1.45      0.17    -1.78    -1.11 1.01     1393
#> biomarker1                 -0.01      0.01    -0.03     0.01 1.00     7162
#> biomarker2                  0.02      0.01     0.00     0.04 1.00     6102
#> groupgroup_2:timetime_2     0.04      0.15    -0.25     0.33 1.00     2286
#> groupgroup_3:timetime_2     0.02      0.15    -0.27     0.32 1.00     2347
#> groupgroup_2:timetime_3    -0.16      0.24    -0.63     0.31 1.01     1733
#> groupgroup_3:timetime_3    -0.19      0.25    -0.68     0.29 1.01     1541
#> groupgroup_2:timetime_4    -0.06      0.25    -0.55     0.42 1.01     1623
#> groupgroup_3:timetime_4    -0.26      0.24    -0.75     0.21 1.00     1517
#> sigma_timetime_1           -0.12      0.04    -0.20    -0.04 1.00     2559
#> sigma_timetime_2            0.00      0.04    -0.07     0.09 1.00     3796
#> sigma_timetime_3           -0.05      0.04    -0.13     0.03 1.00     2346
#> sigma_timetime_4            0.21      0.04     0.13     0.29 1.00     3982
#>                         Tail_ESS
#> Intercept                   2297
#> groupgroup_2                2563
#> groupgroup_3                2097
#> timetime_2                  2360
#> timetime_3                  2455
#> timetime_4                  2103
#> biomarker1                  3250
#> biomarker2                  3060
#> groupgroup_2:timetime_2     2991
#> groupgroup_3:timetime_2     2986
#> groupgroup_2:timetime_3     2596
#> groupgroup_3:timetime_3     2367
#> groupgroup_2:timetime_4     2689
#> groupgroup_3:timetime_4     2562
#> sigma_timetime_1            2658
#> sigma_timetime_2            3159
#> sigma_timetime_3            2891
#> sigma_timetime_4            3364
#> 
#> Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
#> and Tail_ESS are effective sample size measures, and Rhat is the potential
#> scale reduction factor on split chains (at convergence, Rhat = 1).
```

# Marginals

Regardless of the choice of fixed effects formula, `brms.mmrm` performs inference on the marginal distributions at each treatment group and time point of the mean of the following quantities:

1. Response.
2. Change from baseline, if you set `role` to `"change"` in `brm_data()`.
3. Treatment difference, in terms of change from baseline.
4. Effect size: treatment difference divided by the residual standard deviation.

To derive posterior draws of these marginals, use the `brm_marginal_draws()` function.


```r
draws <- brm_marginal_draws(data = data, formula = formula, model = model)
#> Error in brm_formula_has_subgroup(formula): 'list' object cannot be coerced to type 'logical'

draws
#> Error in eval(expr, envir, enclos): object 'draws' not found
```

If you need samples from these marginals averaged across time points, e.g. an "overall effect size", `brm_marginal_draws_average()` can average the draws above across discrete time points (either all or a user-defined subset).


```r
brm_marginal_draws_average(draws = draws, data = data)
#> Error in eval(expr, envir, enclos): object 'draws' not found
```

The `brm_marginal_summaries()` function produces posterior summaries of these marginals, and it includes the Monte Carlo standard error (MCSE) of each estimate.


```r
summaries <- brm_marginal_summaries(draws, level = 0.95)
#> Error in eval(expr, envir, enclos): object 'draws' not found

summaries
#> Error in eval(expr, envir, enclos): object 'summaries' not found
```

The `brm_marginal_probabilities()` function shows posterior probabilities of the form, 

$$
\begin{aligned}
\text{Prob}(\text{treatment effect} > \text{threshold})
\end{aligned}
$$

or 

$$
\begin{aligned}
\text{Prob}(\text{treatment effect} < \text{threshold})
\end{aligned}
$$


```r
brm_marginal_probabilities(
  draws = draws,
  threshold = c(-0.1, 0.1),
  direction = c("greater", "less")
)
#> Error in eval(expr, envir, enclos): object 'draws' not found
```

Finally, `brm_marignal_data()` computes marginal means and confidence intervals on the response variable in the data, along with other summary statistics.


```r
summaries_data <- brm_marginal_data(data = data, level = 0.95)

summaries_data
#> # A tibble: 84 × 4
#>    statistic group   time     value
#>    <chr>     <chr>   <chr>    <dbl>
#>  1 lower     group_1 time_1  1.40  
#>  2 lower     group_1 time_2  2.71  
#>  3 lower     group_1 time_3  1.91  
#>  4 lower     group_1 time_4  0.0151
#>  5 lower     group_2 time_1 -0.150 
#>  6 lower     group_2 time_2  1.23  
#>  7 lower     group_2 time_3  0.218 
#>  8 lower     group_2 time_4 -1.59  
#>  9 lower     group_3 time_1  1.57  
#> 10 lower     group_3 time_2  2.95  
#> # ℹ 74 more rows
```

# Visualization

The `brm_plot_compare()` function compares means and intervals from many different models and data sources in the same plot. First, we need the marginals of the data.


```r
brm_plot_compare(
  data = summaries_data,
  model1 = summaries,
  model2 = summaries
)
#> Error in eval(expr, envir, enclos): object 'summaries' not found
```

If you omit the marginals of the data, you can show inference on change from baseline or the treatment effect.


```r
brm_plot_compare(
  model1 = summaries,
  model2 = summaries,
  marginal = "difference_group" # treatment effect
)
#> Error in eval(expr, envir, enclos): object 'summaries' not found
```

Additional arguments let you control the primary comparison of interest (the color aesthetic), the horizontal axis, and the faceting variable.


```r
brm_plot_compare(
  model1 = summaries,
  model2 = summaries,
  marginal = "difference_group",
  compare = "group",
  axis = "time",
  facet = "source" # model1 vs model2
)
#> Error in eval(expr, envir, enclos): object 'summaries' not found
```

Finally, `brm_plot_draws()` can plot the posterior draws of the response, change from baseline, or treatment difference.


```r
brm_plot_draws(draws = draws$difference_group)
#> Error in eval(expr, envir, enclos): object 'draws' not found
```

The `axis` and `facet` arguments customize the horizontal axis and faceting variable, respectively.


```r
brm_plot_draws(
  draws = draws$difference_group,
  axis = "group",
  facet = "time"
)
#> Error in eval(expr, envir, enclos): object 'draws' not found
```
