#' @title Simulate lapsed outcomes.
#' @export
#' @family simulation
#' @description Simulate lapsed outcomes in a dataset initialized with
#'   [brm_simulate_start()].
#' @details Initialize the simulation with [brm_simulate_start()], then
#'   use [brm_simulate_lapse()] to simulate a simple missingness pattern that
#'   introduces independent uniform sporadic lapses in data collection.
#'   Can be used in conjunction with other simulation functions which accept
#'   a `data` argument, such as [brm_simulate_lapse()].
#'   The earliest time point is treated as baseline and has no missing values.
#' @return The `tibble` from the `data` argument, but with a new or updated
#'   column called `missing` which reflects the missingness pattern
#'   of [brm_simulate_lapse()]. 
#' @param data A `tibble` generated by [brm_simulate_start()].
#' @param rate Positive numeric of length 1 between 0 and 1.
#'   Expected proportion of missing values in the response due to
#'   independent uniform sporadic lapses in data collection.
#' @examples
#' library(magrittr)
#' brm_simulate_start() %>%
#'   brm_simulate_lapse()
brm_simulate_lapse <- function(data, rate = 0.05) {
  if (!("missing" %in% colnames(data))) {
    data$missing <- FALSE
  }
  index <- data$time > min(data$time)
  n <- sum(index)
  missing <- as.logical(stats::rbinom(n = n, size = 1L, prob = rate))
  data$missing[index] <- data$missing[index] | missing
  data
}
