#' @title Simulate dropouts.
#' @export
#' @family simulation
#' @description Simulate dropouts in a dataset initialized with
#'   [brm_simulate_start()].
#' @details Initialize the simulation with [brm_simulate_start()], then
#'   use [brm_simulate_dropout()] to simulate a simple missingness pattern that
#'   introduces a simple dropout pattern in the data. A dropout is an
#'   intercurrent event when data collection for a patient stops permanently,
#'   causing the outcomes for that patient to be missing during and after
#'   the dropout occurred. The first time point is assumed to be baseline,
#'   so dropout is there. Dropouts are equally likely to occur at each of
#'   the post-baseline time points.
#' @return The `tibble` from the `data` argument, but with a new or updated
#'   column called `missing` which reflects the missingness pattern
#'   of [brm_simulate_dropout()]. 
#' @param data A `tibble` generated by [brm_simulate_start()].
#' @param rate Positive numeric of length 1 between 0 and 1.
#'   Expected dropout proportion observed by the final time point. Earlier time
#'   points may have lower observed dropout proportions.
#' @examples
#' library(magrittr)
#' brm_simulate_start() %>%
#'   brm_simulate_dropout()
brm_simulate_dropout <- function(data, rate) {
  if (!("missing" %in% colnames(data))) {
    data$missing <- FALSE
  }
  rows_baseline <- dplyr::filter(data, time == min(time))
  data <- dplyr::filter(data, time > min(time))
  data <- dplyr::arrange(data, group, patient, time)
  data <- dplyr::group_by(data, patient)
  n_time <- length(unique(data$time))
  data <- dplyr::mutate(
    .data = data,
    missing = missing | brm_dropout_patient(rate, n_time)
  )
  data <- dplyr::ungroup(data)
  data <- dplyr::bind_rows(rows_baseline, data)
  dplyr::arrange(data, group, patient, time)
}

brm_dropout_patient <- function(rate, n_time) {
  if_any(
    as.logical(rbinom(n = 1L, size = 1L, prob = rate)),
    seq_len(n_time) >= sample.int(n = n_time, size = 1L),
    rep(FALSE, n_time)
  )
}
